In [207]:
#importanto os paranaue
import pandas as pd
import numpy as np

In [208]:
!ls

analise_de_residuos.ipynb  novos_dados.csv
dados			   Py_DS_ML_Bootcamp-master
dados.csv		   README.md
dados.json		   residencia.ipynb
figures			   residentes.xlsx
MEDIUM_NoteBook-master	   savio_regressao_logistica.ipynb
model


The class label indicates if the person has a coronary heart disease: negative (0) or positive (1). 

Attributes description: 
- sbp: systolic blood pressure 
- tobacco: cumulative tobacco (kg) 
- ldl: low densiity lipoprotein cholesterol 
- adiposity 
- famhist: family history of heart disease (Present, Absent) 
- typea: type-A behavior 
- obesity 
- alcohol: current alcohol consumption 
- age: age at onset

In [209]:
df = pd.read_csv('dados.csv')
df.head()

sbp  tobacco   ldl  adiposity  famhist  typea  obesity  alcohol  age  chd
1  160    12.00  5.73      23.11  Present     49    25.30    97.20   52    1
2  144     0.01  4.41      28.61   Absent     55    28.87     2.06   63    1
3  118     0.08  3.48      32.28  Present     52    29.14     3.81   46    0
4  170     7.50  6.41      38.03  Present     51    31.99    24.26   58    1
5  134    13.60  3.50      27.78  Present     60    25.99    57.34   49    1

### Balanceando os dados por undersample

In [210]:
df.chd.sum() / df.chd.shape[0]

0.3463203463203463

In [211]:
df_zeros = df.loc[df.chd==0]
df_zeros = df_zeros.iloc[:(int(df_zeros.shape[0]/2))]
df_zeros

sbp  tobacco   ldl  adiposity  famhist  typea  obesity  alcohol  age  chd
3    118     0.08  3.48      32.28  Present     52    29.14     3.81   46    0
6    132     6.20  6.47      36.21  Present     62    30.77    14.14   45    0
7    142     4.05  3.38      16.20   Absent     59    20.81     2.62   38    0
9    114     0.00  3.83      19.40  Present     49    24.86     2.49   29    0
13   118     0.00  1.88      10.05   Absent     59    21.57     0.00   17    0
..   ...      ...   ...        ...      ...    ...      ...      ...  ...  ...
226  143     5.04  4.86      23.59   Absent     58    24.69    18.72   42    0
232  136    13.20  7.18      35.95   Absent     48    29.19     0.00   62    0
234  122     0.00  3.76      24.59   Absent     56    24.36     0.00   30    0
235  138     0.00  3.24      27.68   Absent     60    25.70    88.66   29    0
237  126     5.50  3.78      34.15   Absent     55    28.85     3.18   61    0

[151 rows x 10 columns]

In [212]:
df_ones = df.loc[df.chd==1]
df_ones

sbp  tobacco   ldl  adiposity  famhist  typea  obesity  alcohol  age  chd
1    160    12.00  5.73      23.11  Present     49    25.30    97.20   52    1
2    144     0.01  4.41      28.61   Absent     55    28.87     2.06   63    1
4    170     7.50  6.41      38.03  Present     51    31.99    24.26   58    1
5    134    13.60  3.50      27.78  Present     60    25.99    57.34   49    1
8    114     4.08  4.59      14.60  Present     62    23.11     6.72   58    1
..   ...      ...   ...        ...      ...    ...      ...      ...  ...  ...
455  124     1.60  7.22      39.68  Present     36    31.50     0.00   51    1
456  146     0.64  4.82      28.02   Absent     60    28.11     8.23   39    1
457  128     2.24  2.83      26.48   Absent     48    23.96    47.42   27    1
460  182     4.20  4.41      32.10   Absent     52    28.61    18.72   52    1
463  132     0.00  4.82      33.41  Present     62    14.70     0.00   46    1

[160 rows x 10 columns]

### DUMMIES DA VARIAVEL CATEGORICA 

In [213]:
df = pd.concat((df_ones, df_zeros))
df

sbp  tobacco   ldl  adiposity  famhist  typea  obesity  alcohol  age  chd
1    160    12.00  5.73      23.11  Present     49    25.30    97.20   52    1
2    144     0.01  4.41      28.61   Absent     55    28.87     2.06   63    1
4    170     7.50  6.41      38.03  Present     51    31.99    24.26   58    1
5    134    13.60  3.50      27.78  Present     60    25.99    57.34   49    1
8    114     4.08  4.59      14.60  Present     62    23.11     6.72   58    1
..   ...      ...   ...        ...      ...    ...      ...      ...  ...  ...
226  143     5.04  4.86      23.59   Absent     58    24.69    18.72   42    0
232  136    13.20  7.18      35.95   Absent     48    29.19     0.00   62    0
234  122     0.00  3.76      24.59   Absent     56    24.36     0.00   30    0
235  138     0.00  3.24      27.68   Absent     60    25.70    88.66   29    0
237  126     5.50  3.78      34.15   Absent     55    28.85     3.18   61    0

[311 rows x 10 columns]

### Dados Balanceados

In [214]:
df.chd.sum() / df.chd.shape[0]

0.5144694533762058

In [215]:
df = pd.concat((df, pd.get_dummies(df.famhist)), axis=1)
df.drop('famhist', inplace=True, axis=1)

In [216]:
df.head()

sbp  tobacco   ldl  adiposity  typea  obesity  alcohol  age  chd  Absent  \
1  160    12.00  5.73      23.11     49    25.30    97.20   52    1       0   
2  144     0.01  4.41      28.61     55    28.87     2.06   63    1       1   
4  170     7.50  6.41      38.03     51    31.99    24.26   58    1       0   
5  134    13.60  3.50      27.78     60    25.99    57.34   49    1       0   
8  114     4.08  4.59      14.60     62    23.11     6.72   58    1       0   

   Present  
1        1  
2        0  
4        1  
5        1  
8        1

In [217]:
df.columns

Index(['sbp', 'tobacco', 'ldl', 'adiposity', 'typea', 'obesity', 'alcohol',
       'age', 'chd', 'Absent', 'Present'],
      dtype='object')

In [218]:
colunas = ['sbp', 'tobacco', 'ldl', 'adiposity', 'typea', 'obesity', 'alcohol', 'age']

### Normalizando os dados

In [219]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
df_s = df.copy()
df_s[colunas] = scaler.fit_transform(df[colunas])
df_s

sbp   tobacco       ldl  adiposity     typea   obesity   alcohol  \
1    0.500000  0.384615  0.331010   0.414502  0.553846  0.332497  0.660371   
2    0.362069  0.000321  0.239024   0.580665  0.646154  0.444479  0.013996   
4    0.586207  0.240385  0.378397   0.865257  0.584615  0.542346  0.164821   
5    0.275862  0.435897  0.175610   0.555589  0.723077  0.354141  0.389565   
8    0.103448  0.130769  0.251568   0.157402  0.753846  0.263802  0.045655   
..        ...       ...       ...        ...       ...       ...       ...   
226  0.353448  0.161538  0.270383   0.429003  0.692308  0.313363  0.127183   
232  0.293103  0.423077  0.432056   0.802417  0.538462  0.454517  0.000000   
234  0.172414  0.000000  0.193728   0.459215  0.661538  0.303011  0.000000   
235  0.310345  0.000000  0.157491   0.552568  0.723077  0.345044  0.602351   
237  0.206897  0.176282  0.195122   0.748036  0.646154  0.443852  0.021605   

          age  chd  Absent  Present  
1    0.755102    1       0        1  
2    0.979592    1       1        0  
4    0.877551    1       0        1  
5    0.693878    1       0        1  
8    0.877551    1       0        1  
..        ...  ...     ...      ...  
226  0.551020    0       1        0  
232  0.959184    0       1        0  
234  0.306122    0       1        0  
235  0.285714    0       1        0  
237  0.938776    0       1        0  

[311 rows x 11 columns]

* Lembrar de treinar o algorimo from scratch quando estudar js

### Aplicando regrecao logistica

In [220]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [221]:
y = df_s['chd']
X = df_s.drop('chd', axis=1)

In [222]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
X_test.to_csv('novos_dados.csv', index=False)

In [223]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
predito = lr.predict(X_test)

In [224]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, predito)

print(cm)

[[30 17]
 [ 9 47]]


In [225]:
from sklearn.metrics import classification_report

print(classification_report(y_test, predito))

              precision    recall  f1-score   support

           0       0.77      0.64      0.70        47
           1       0.73      0.84      0.78        56

    accuracy                           0.75       103
   macro avg       0.75      0.74      0.74       103
weighted avg       0.75      0.75      0.74       103



Significativas melhoras no recall apos balanceamento dos dados

In [226]:
import pickle
with open('model.pkl', 'wb') as file:
    pickle.dump(lr, file)

In [227]:
predicted_proba = lr.predict_proba(X_test)
predicted_proba.shape

(103, 2)

In [228]:
predicted_proba[:,1]

array([0.69933059, 0.81351737, 0.74910924, 0.75654949, 0.38709128,
       0.70633793, 0.77671768, 0.28759658, 0.27519909, 0.51031533,
       0.62526234, 0.41040683, 0.33659163, 0.24935183, 0.2274853 ,
       0.32131973, 0.6908755 , 0.63259833, 0.15478028, 0.58653647,
       0.54867786, 0.45720731, 0.70389214, 0.30778296, 0.3551684 ,
       0.49045709, 0.66667071, 0.74187089, 0.78026201, 0.30909848,
       0.34183943, 0.77610803, 0.68639832, 0.29438002, 0.6212672 ,
       0.75170289, 0.74902578, 0.76052611, 0.7678897 , 0.5574666 ,
       0.69443709, 0.51282443, 0.19781165, 0.52235666, 0.17576531,
       0.15327342, 0.69297803, 0.66795376, 0.30912024, 0.60870503,
       0.64592552, 0.55055892, 0.85295376, 0.49190566, 0.1379625 ,
       0.28041217, 0.15203766, 0.45885048, 0.27963746, 0.38731594,
       0.2399732 , 0.4729673 , 0.56214629, 0.5538454 , 0.68078416,
       0.54112133, 0.24288187, 0.64945586, 0.6200584 , 0.44033405,
       0.73541452, 0.64806464, 0.42029707, 0.50265774, 0.62598

In [229]:
lr.intercept_

array([-1.85997439])

In [230]:
lr.coef_

array([[ 0.00379281,  1.04090026,  0.47792532,  0.36497716,  0.76172169,
        -0.13964523,  0.80445294,  1.58242142, -0.448951  ,  0.44890235]])

In [231]:
import numpy as np
import pandas as pd
import pickle

class SavioLogisticModel():
      
        def __init__(self, model_file):
            with open('model.pkl','rb') as model_file:
                self.reg = pickle.load(model_file)
                self.data = None
                
        def load_new_data(self, data_file):
            df = pd.read_csv(data_file,delimiter=',')
            df = df.sample(10)
            self.data = df.copy()
            self.preprocessed_data = df.copy()
            
        def predicted_probability(self):
            if (self.data is not None):  
                pred = self.reg.predict_proba(self.data)
                return pred
            
        def predicted_output_category(self):
            if (self.data is not None):
                pred_outputs = self.reg.predict(self.data)
                return pred_outputs
            
        def predicted_outputs(self):
            if (self.data is not None):
                self.preprocessed_data['Probabilidade'] = 0
                self.preprocessed_data['Predito'] = 0
                self.preprocessed_data['Probabilidade'] = self.reg.predict_proba(self.data)[:,1]
                self.preprocessed_data['Predito'] = self.reg.predict(self.data)
                return self.preprocessed_data

In [232]:
model = SavioLogisticModel('model.pkl')
model.load_new_data('novos_dados.csv')
model.predicted_probability()[:,1]
model.predicted_output_category()
model.predicted_outputs()

sbp   tobacco       ldl  adiposity     typea   obesity   alcohol  \
27  0.396552  0.153846  0.356098   0.820544  0.769231  0.336888  0.005979   
66  0.241379  0.055128  0.117073   0.029909  0.846154  0.097553  0.075413   
87  0.327586  0.275641  0.203484   0.687915  0.600000  0.433187  0.075481   
15  0.431034  0.096154  0.255052   0.661631  0.430769  0.459222  0.030777   
86  0.120690  0.256410  0.400697   0.586707  0.430769  0.377666  0.278144   
61  0.689655  0.134615  0.239024   0.686103  0.600000  0.436324  0.127183   
4   0.431034  0.028846  0.567247   0.629607  0.661538  0.437265  0.002514   
29  0.362069  0.000000  0.199303   0.281873  0.661538  0.232120  0.032611   
22  0.534483  0.179487  0.152613   0.652266  0.476923  0.354141  0.293498   
0   0.172414  0.102564  0.181882   0.395770  0.492308  0.321832  0.245737   

         age  Absent  Present  Probabilidade  Predito  
27  0.816327       0        1       0.741871        1  
66  0.224490       1        0       0.242882        0  
87  1.000000       0        1       0.779901        1  
15  0.510204       1        0       0.321320        0  
86  0.673469       0        1       0.695672        1  
61  0.755102       1        0       0.472967        0  
4   0.551020       1        0       0.387091        0  
29  0.510204       1        0       0.309098        0  
22  0.775510       0        1       0.703892        1  
0   0.877551       0        1       0.699331        1

In [233]:
df_json = model.predicted_outputs()

In [234]:
import requests
  
# api-endpoint 
URL = "http://127.0.0.1:3000/store"
  
# location given here 
location = "store"
  
# defining a params dict for the parameters to be sent to the API 
PARAMS = {'address':location} 
  
# sending get request and saving the response as response object 
r = requests.get(url = URL) 
print(r)
# extracting data in json format 
data = r.json()
print(data)
# extracting latitude, longitude and formatted address  
# # of the first matching location 
# latitude = data['results'][0]['geometry']['location']['lat'] 
# longitude = data['results'][0]['geometry']['location']['lng'] 
# formatted_address = data['results'][0]['formatted_address'] 
  
# # printing the output 
# print("Latitude:%s\nLongitude:%s\nFormatted Address:%s"
#       %(latitude, longitude,formatted_address)) 

<Response [200]>
{'stores': [{'items': [{'name': 'My item', 'price': 15.99}], 'name': 'minha loja'}]}


In [297]:
# importing the requests library 
import requests 
  
# defining the api-endpoint  
API_ENDPOINT = "http://127.0.0.1:3000/model"
  
df_to_dict_data = X_test.sample(5).to_dict(orient='list')
post_data = {'dataset ID': "makis", 'date start': "1", 'date end': "2", 'payload': df_to_dict_data}

# sending post request and saving response as response object 
r = requests.post(url = API_ENDPOINT, json = post_data) 
df = r.json()
# extracting response text  
#pastebin_url = r.text 
#print("The pastebin URL is:%s"%pastebin_url) 
pd.DataFrame(df)

Absent  Predito  Present  Probabilidade  adiposity       age   alcohol  \
0       1        1        0       0.524876   0.426888  1.000000  0.130444   
1       0        1        1       0.706338   0.558912  0.938776  0.000000   
2       1        0        0       0.457207   0.720242  0.714286  0.041919   
3       1        0        0       0.153273   0.032024  0.040816  0.013996   
4       1        0        0       0.279637   0.451360  0.469388  0.068483   

        ldl   obesity       sbp   tobacco     typea  
0  0.208362  0.285759  0.224138  0.023397  0.630769  
1  0.296864  0.370765  0.172414  0.128205  0.492308  
2  0.222300  0.397114  0.896552  0.000000  0.861538  
3  0.058537  0.231179  0.241379  0.000000  0.676923  
4  0.231359  0.393036  0.327586  0.014423  0.430769

In [299]:
df_to_dict_data

{'sbp': [0.22413793103448276,
  0.1724137931034483,
  0.8965517241379309,
  0.2413793103448275,
  0.3275862068965517],
 'tobacco': [0.0233974358974359,
  0.12820512820512822,
  0.0,
  0.0,
  0.014423076923076926],
 'ldl': [0.20836236933797908,
  0.2968641114982578,
  0.22229965156794423,
  0.05853658536585367,
  0.23135888501742158],
 'adiposity': [0.42688821752265854,
  0.5589123867069485,
  0.7202416918429002,
  0.03202416918429002,
  0.45135951661631407],
 'typea': [0.6307692307692307,
  0.4923076923076923,
  0.8615384615384616,
  0.676923076923077,
  0.43076923076923074],
 'obesity': [0.2857590966122961,
  0.37076537013801764,
  0.3971141781681305,
  0.2311794228356337,
  0.39303638644918454],
 'alcohol': [0.13044364426931176,
  0.0,
  0.041918608601127796,
  0.013995515999728243,
  0.06848291324138868],
 'age': [1.0,
  0.9387755102040816,
  0.7142857142857144,
  0.04081632653061229,
  0.46938775510204084],
 'Absent': [1, 0, 1, 1, 1],
 'Present': [0, 1, 0, 0, 0]}

In [243]:
#dataset = dataset.to_dict(orient='list')
#post_data = {'dataset ID': "makis", 'date start': "1", 'date end': "2", 'payload': dataset}
#url = "http://localhost:8081/upload_dataset"
#r = requests.post(url, json=post_data)

In [315]:
dictionary = {'sbp': [0.17],
 'tobacco': [0.1],
 'ldl': [0.18],
 'adiposity': [0.4],
 'typea': [0.4],
 'obesity': [0.20],
 'alcohol': [0.24],
 'age': [0.87],
 'Absent': [0.0],
 'Present': [1.0]}

In [318]:
url = "http://127.0.0.1:3000/model"
post_data = {'data_set ID': '1', 'payload':dictionary}
r = requests.post(url = url, json = post_data)
df = r.json()
pd.DataFrame(df)
url = "http://127.0.0.1:3000/model"
post_data = {'dataset ID': "makis", 'date start': "1", 'date end': "2", 'payload': dictionary}

type(post_data)

dict

In [320]:
import json
post_data = json.dumps(post_data)
type(post_data)

str

In [322]:
r = requests.post(url = url, post_data)
df = r.json()
pd.DataFrame(df)

SyntaxError: positional argument follows keyword argument (<ipython-input-322-5c16f23b4ba7>, line 1)