In [1]:
#importanto os paranaue
import pandas as pd
import numpy as np

In [4]:
!dir

 O volume na unidade C não tem nome.
 O Número de Série do Volume é DC82-FD6F

 Pasta de C:\Users\everl\Documents\GitHub\Pocket_Manual_Jupyter_Notebooks\03_Machine_Learning

09/03/2020  14:26    <DIR>          .
09/03/2020  14:26    <DIR>          ..
09/03/2020  14:26    <DIR>          .ipynb_checkpoints
17/02/2020  12:50    <DIR>          00_Database
17/02/2020  12:50    <DIR>          00_figuras
17/02/2020  12:50    <DIR>          00_modelos
17/02/2020  12:50           122.587 01_savio_analise_de_residuos.ipynb
09/03/2020  14:26            68.213 03_savio_regressao_logistica.ipynb
17/02/2020  12:50            11.932 NLP.ipynb
17/02/2020  12:50             3.867 NLP_Token.ipynb
17/02/2020  12:50            17.100 ocr_restful_get.ipynb
               5 arquivo(s)        223.699 bytes
               6 pasta(s)   22.000.599.040 bytes disponíveis


The class label indicates if the person has a coronary heart disease: negative (0) or positive (1). 

Attributes description: 
- sbp: systolic blood pressure 
- tobacco: cumulative tobacco (kg) 
- ldl: low densiity lipoprotein cholesterol 
- adiposity 
- famhist: family history of heart disease (Present, Absent) 
- typea: type-A behavior 
- obesity 
- alcohol: current alcohol consumption 
- age: age at onset

In [6]:
df = pd.read_csv('00_database/dados.csv')
df.head()

sbp  tobacco   ldl  adiposity  famhist  typea  obesity  alcohol  age  chd
1  160    12.00  5.73      23.11  Present     49    25.30    97.20   52    1
2  144     0.01  4.41      28.61   Absent     55    28.87     2.06   63    1
3  118     0.08  3.48      32.28  Present     52    29.14     3.81   46    0
4  170     7.50  6.41      38.03  Present     51    31.99    24.26   58    1
5  134    13.60  3.50      27.78  Present     60    25.99    57.34   49    1

### Balanceando os dados por undersample

In [7]:
df.chd.sum() / df.chd.shape[0]

0.3463203463203463

In [8]:
df_zeros = df.loc[df.chd==0]
df_zeros = df_zeros.iloc[:(int(df_zeros.shape[0]/2))]
df_zeros

sbp  tobacco   ldl  adiposity  famhist  typea  obesity  alcohol  age  chd
3    118     0.08  3.48      32.28  Present     52    29.14     3.81   46    0
6    132     6.20  6.47      36.21  Present     62    30.77    14.14   45    0
7    142     4.05  3.38      16.20   Absent     59    20.81     2.62   38    0
9    114     0.00  3.83      19.40  Present     49    24.86     2.49   29    0
13   118     0.00  1.88      10.05   Absent     59    21.57     0.00   17    0
..   ...      ...   ...        ...      ...    ...      ...      ...  ...  ...
226  143     5.04  4.86      23.59   Absent     58    24.69    18.72   42    0
232  136    13.20  7.18      35.95   Absent     48    29.19     0.00   62    0
234  122     0.00  3.76      24.59   Absent     56    24.36     0.00   30    0
235  138     0.00  3.24      27.68   Absent     60    25.70    88.66   29    0
237  126     5.50  3.78      34.15   Absent     55    28.85     3.18   61    0

[151 rows x 10 columns]

In [9]:
df_ones = df.loc[df.chd==1]
df_ones

sbp  tobacco   ldl  adiposity  famhist  typea  obesity  alcohol  age  chd
1    160    12.00  5.73      23.11  Present     49    25.30    97.20   52    1
2    144     0.01  4.41      28.61   Absent     55    28.87     2.06   63    1
4    170     7.50  6.41      38.03  Present     51    31.99    24.26   58    1
5    134    13.60  3.50      27.78  Present     60    25.99    57.34   49    1
8    114     4.08  4.59      14.60  Present     62    23.11     6.72   58    1
..   ...      ...   ...        ...      ...    ...      ...      ...  ...  ...
455  124     1.60  7.22      39.68  Present     36    31.50     0.00   51    1
456  146     0.64  4.82      28.02   Absent     60    28.11     8.23   39    1
457  128     2.24  2.83      26.48   Absent     48    23.96    47.42   27    1
460  182     4.20  4.41      32.10   Absent     52    28.61    18.72   52    1
463  132     0.00  4.82      33.41  Present     62    14.70     0.00   46    1

[160 rows x 10 columns]

### DUMMIES DA VARIAVEL CATEGORICA 

In [10]:
df = pd.concat((df_ones, df_zeros))
df

sbp  tobacco   ldl  adiposity  famhist  typea  obesity  alcohol  age  chd
1    160    12.00  5.73      23.11  Present     49    25.30    97.20   52    1
2    144     0.01  4.41      28.61   Absent     55    28.87     2.06   63    1
4    170     7.50  6.41      38.03  Present     51    31.99    24.26   58    1
5    134    13.60  3.50      27.78  Present     60    25.99    57.34   49    1
8    114     4.08  4.59      14.60  Present     62    23.11     6.72   58    1
..   ...      ...   ...        ...      ...    ...      ...      ...  ...  ...
226  143     5.04  4.86      23.59   Absent     58    24.69    18.72   42    0
232  136    13.20  7.18      35.95   Absent     48    29.19     0.00   62    0
234  122     0.00  3.76      24.59   Absent     56    24.36     0.00   30    0
235  138     0.00  3.24      27.68   Absent     60    25.70    88.66   29    0
237  126     5.50  3.78      34.15   Absent     55    28.85     3.18   61    0

[311 rows x 10 columns]

### Dados Balanceados

In [11]:
df.chd.sum() / df.chd.shape[0]

0.5144694533762058

In [12]:
df = pd.concat((df, pd.get_dummies(df.famhist)), axis=1)
df.drop('famhist', inplace=True, axis=1)

In [13]:
df.head()

sbp  tobacco   ldl  adiposity  typea  obesity  alcohol  age  chd  Absent  \
1  160    12.00  5.73      23.11     49    25.30    97.20   52    1       0   
2  144     0.01  4.41      28.61     55    28.87     2.06   63    1       1   
4  170     7.50  6.41      38.03     51    31.99    24.26   58    1       0   
5  134    13.60  3.50      27.78     60    25.99    57.34   49    1       0   
8  114     4.08  4.59      14.60     62    23.11     6.72   58    1       0   

   Present  
1        1  
2        0  
4        1  
5        1  
8        1

In [14]:
df.columns

Index(['sbp', 'tobacco', 'ldl', 'adiposity', 'typea', 'obesity', 'alcohol',
       'age', 'chd', 'Absent', 'Present'],
      dtype='object')

In [15]:
colunas = ['sbp', 'tobacco', 'ldl', 'adiposity', 'typea', 'obesity', 'alcohol', 'age']

### Normalizando os dados

In [16]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
df_s = df.copy()
df_s[colunas] = scaler.fit_transform(df[colunas])
df_s

sbp   tobacco       ldl  adiposity     typea   obesity   alcohol  \
1    0.500000  0.384615  0.331010   0.414502  0.553846  0.332497  0.660371   
2    0.362069  0.000321  0.239024   0.580665  0.646154  0.444479  0.013996   
4    0.586207  0.240385  0.378397   0.865257  0.584615  0.542346  0.164821   
5    0.275862  0.435897  0.175610   0.555589  0.723077  0.354141  0.389565   
8    0.103448  0.130769  0.251568   0.157402  0.753846  0.263802  0.045655   
..        ...       ...       ...        ...       ...       ...       ...   
226  0.353448  0.161538  0.270383   0.429003  0.692308  0.313363  0.127183   
232  0.293103  0.423077  0.432056   0.802417  0.538462  0.454517  0.000000   
234  0.172414  0.000000  0.193728   0.459215  0.661538  0.303011  0.000000   
235  0.310345  0.000000  0.157491   0.552568  0.723077  0.345044  0.602351   
237  0.206897  0.176282  0.195122   0.748036  0.646154  0.443852  0.021605   

          age  chd  Absent  Present  
1    0.755102    1       0        1  
2    0.979592    1       1        0  
4    0.877551    1       0        1  
5    0.693878    1       0        1  
8    0.877551    1       0        1  
..        ...  ...     ...      ...  
226  0.551020    0       1        0  
232  0.959184    0       1        0  
234  0.306122    0       1        0  
235  0.285714    0       1        0  
237  0.938776    0       1        0  

[311 rows x 11 columns]

* Lembrar de treinar o algorimo from scratch quando estudar js

### Aplicando regrecao logistica

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [18]:
y = df_s['chd']
X = df_s.drop('chd', axis=1)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
X_test.to_csv('novos_dados.csv', index=False)

In [20]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
predito = lr.predict(X_test)

C:\Users\everl\Anaconda3\envs\env01\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [21]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, predito)

print(cm)

[[30 17]
 [ 9 47]]


In [22]:
from sklearn.metrics import classification_report

print(classification_report(y_test, predito))

              precision    recall  f1-score   support

           0       0.77      0.64      0.70        47
           1       0.73      0.84      0.78        56

    accuracy                           0.75       103
   macro avg       0.75      0.74      0.74       103
weighted avg       0.75      0.75      0.74       103



Significativas melhoras no recall apos balanceamento dos dados

In [23]:
import pickle
with open('model.pkl', 'wb') as file:
    pickle.dump(lr, file)

In [24]:
predicted_proba = lr.predict_proba(X_test)
predicted_proba.shape

(103, 2)

In [25]:
predicted_proba[:,1]

array([0.71492709, 0.7986812 , 0.75028333, 0.7309109 , 0.38002753,
       0.71874927, 0.78152495, 0.29397297, 0.29399131, 0.50921465,
       0.59513542, 0.44406363, 0.36352579, 0.26257858, 0.24128082,
       0.33643794, 0.67611742, 0.65185943, 0.17136252, 0.570547  ,
       0.56033366, 0.42622702, 0.71350047, 0.32255286, 0.35663381,
       0.47041417, 0.68638796, 0.73297423, 0.77838752, 0.31853693,
       0.34836906, 0.77524225, 0.66179035, 0.29636008, 0.60979933,
       0.7651919 , 0.75113374, 0.76138937, 0.76551328, 0.58610073,
       0.70499205, 0.52920248, 0.22897296, 0.52281862, 0.19055649,
       0.16949236, 0.66869059, 0.67237236, 0.31236466, 0.60234565,
       0.65667884, 0.56318508, 0.84172961, 0.48693823, 0.14452067,
       0.29846181, 0.16944722, 0.48858164, 0.29956919, 0.39664018,
       0.2593154 , 0.46393095, 0.57993059, 0.54726529, 0.67568922,
       0.52685326, 0.25286845, 0.66144339, 0.59937027, 0.44318632,
       0.73115499, 0.60856633, 0.42170652, 0.50653683, 0.64032

In [26]:
lr.intercept_

array([-0.9679569])

In [27]:
lr.coef_

array([[-0.08330937,  1.04086211,  0.3991179 ,  0.329112  ,  0.43870475,
        -0.25386012,  0.7546745 ,  1.47704988, -0.94419769, -0.02375921]])

In [28]:
import numpy as np
import pandas as pd
import pickle

class SavioLogisticModel():
      
        def __init__(self, model_file):
            with open('model.pkl','rb') as model_file:
                self.reg = pickle.load(model_file)
                self.data = None
                
        def load_new_data(self, data_file):
            df = pd.read_csv(data_file,delimiter=',')
            df = df.sample(10)
            self.data = df.copy()
            self.preprocessed_data = df.copy()
            
        def predicted_probability(self):
            if (self.data is not None):  
                pred = self.reg.predict_proba(self.data)
                return pred
            
        def predicted_output_category(self):
            if (self.data is not None):
                pred_outputs = self.reg.predict(self.data)
                return pred_outputs
            
        def predicted_outputs(self):
            if (self.data is not None):
                self.preprocessed_data['Probabilidade'] = 0
                self.preprocessed_data['Predito'] = 0
                self.preprocessed_data['Probabilidade'] = self.reg.predict_proba(self.data)[:,1]
                self.preprocessed_data['Predito'] = self.reg.predict(self.data)
                return self.preprocessed_data

In [29]:
model = SavioLogisticModel('model.pkl')
model.load_new_data('novos_dados.csv')
model.predicted_probability()[:,1]
model.predicted_output_category()
model.predicted_outputs()

sbp   tobacco       ldl  adiposity     typea   obesity   alcohol  \
60   0.224138  0.013462  0.252265   0.522356  0.430769  0.510351  0.070181   
97   0.189655  0.448718  0.365854   0.802719  0.492308  0.482748  0.000000   
74   0.241379  0.083654  0.121254   0.410876  0.584615  0.363551  0.090835   
5    0.172414  0.128205  0.296864   0.558912  0.492308  0.370765  0.000000   
46   0.482759  0.115385  0.138676   0.625982  0.769231  0.374529  0.733745   
101  0.206897  0.000000  0.348432   0.594260  0.661538  0.335320  0.078266   
61   0.689655  0.134615  0.239024   0.686103  0.600000  0.436324  0.127183   
0    0.172414  0.102564  0.181882   0.395770  0.492308  0.321832  0.245737   
48   0.275862  0.088141  0.315679   0.506949  0.676923  0.475847  0.056594   
93   0.189655  0.025962  0.360976   0.067069  0.338462  0.212359  0.071268   

          age  Absent  Present  Probabilidade  Predito  
60   0.326531       1        0       0.259315        0  
97   0.897959       0        1       0.784062        1  
74   0.734694       0        1       0.640326        1  
5    0.938776       0        1       0.718749        1  
46   1.000000       1        0       0.668691        1  
101  1.000000       0        1       0.744007        1  
61   0.755102       1        0       0.463931        0  
0    0.877551       0        1       0.714927        1  
48   0.367347       1        0       0.312365        0  
93   0.224490       1        0       0.221863        0

In [30]:
df_json = model.predicted_outputs()

In [33]:
import requests
  
# api-endpoint 
URL = "http://127.0.0.1:5000/store"
  
# location given here 
location = "store"
  
# defining a params dict for the parameters to be sent to the API 
PARAMS = {'address':location} 
  
# sending get request and saving the response as response object 
r = requests.get(url = URL) 
print(r)
# extracting data in json format 
data = r.json()
print(data)
# extracting latitude, longitude and formatted address  
# # of the first matching location 
# latitude = data['results'][0]['geometry']['location']['lat'] 
# longitude = data['results'][0]['geometry']['location']['lng'] 
# formatted_address = data['results'][0]['formatted_address'] 
  
# # printing the output 
# print("Latitude:%s\nLongitude:%s\nFormatted Address:%s"
#       %(latitude, longitude,formatted_address)) 

<Response [404]>


JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [67]:
# importing the requests library 
import requests 
  
# defining the api-endpoint  
API_ENDPOINT = "http://127.0.0.1:5000/model"
  
df_to_dict_data = X_test.sample(5).to_dict(orient='list')
post_data = {'dataset ID': "makis", 'date start': "1", 'date end': "2", 'payload': df_to_dict_data}

# sending post request and saving response as response object 
r = requests.post(url = API_ENDPOINT, json = post_data) 
df = r.json()
# extracting response text  
#pastebin_url = r.text 
#print("The pastebin URL is:%s"%pastebin_url) 
pd.DataFrame(df)

Predito  Probabilidade
0        1       0.751703
1        0       0.154780
2        0       0.239973
3        1       0.584471
4        1       0.749026

In [68]:
df_to_dict_data

{'sbp': [0.293103448275862,
  0.13793103448275856,
  0.22413793103448276,
  0.18965517241379304,
  0.4137931034482759],
 'tobacco': [0.2820512820512821,
  0.0,
  0.013461538461538462,
  0.49679487179487186,
  0.1121794871794872],
 'ldl': [0.25853658536585367,
  0.0627177700348432,
  0.2522648083623693,
  0.28362369337979093,
  0.41881533101045293],
 'adiposity': [0.8060422960725075,
  0.01993957703927496,
  0.522356495468278,
  0.44320241691842893,
  0.48338368580060426],
 'typea': [0.38461538461538464,
  0.7076923076923078,
  0.43076923076923074,
  0.5076923076923077,
  0.5692307692307692],
 'obesity': [0.3720200752823087,
  0.21549560853199506,
  0.5103513174404015,
  0.26725219573400255,
  0.2713299874529486],
 'alcohol': [0.018887152659827433,
  0.0,
  0.07018139819281201,
  0.0,
  0.1595217066376792],
 'age': [0.9795918367346939,
  0.04081632653061229,
  0.32653061224489793,
  0.9387755102040816,
  0.9387755102040816],
 'Absent': [0, 1, 1, 1, 0],
 'Present': [1, 0, 0, 0, 1]}

In [55]:
#dataset = dataset.to_dict(orient='list')
#post_data = {'dataset ID': "makis", 'date start': "1", 'date end': "2", 'payload': dataset}
#url = "http://localhost:8081/upload_dataset"
#r = requests.post(url, json=post_data)

In [60]:
dictionary = {'sbp': [0.17],
 'tobacco': [0.1],
 'ldl': [0.18],
 'adiposity': [0.5],
 'typea': [0.4],
 'obesity': [0.20],
 'alcohol': [0.24],
 'age': [0.87],
 'Absent': [0.0],
 'Present': [1.0]}

In [64]:
url = "http://127.0.0.1:5000/model"
post_data = {'data_set ID': '1', 'payload':dictionary}
r = requests.post(url = url, json = post_data)
df = r.json()
pd.DataFrame(df)
url = "http://127.0.0.1:5000/model"
post_data = {'dataset ID': "makis", 'date start': "1", 'date end': "2", 'payload': dictionary}

type(post_data)

dict

In [65]:
# import json
# post_data = json.dumps(post_data)
# type(post_data)

In [66]:
r = requests.post(url = url, json = post_data)
df = r.json()
pd.DataFrame(df)

Predito  Probabilidade
0        1       0.691835